// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $BatchPredictor from "./islands/BatchPredictor.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $GenderPredictor from "./islands/GenderPredictor.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $ModelInfo from "./islands/ModelInfo.tsx";
import * as $TabNavigation from "./islands/TabNavigation.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BatchPredictor.tsx": $BatchPredictor,
    "./islands/Counter.tsx": $Counter,
    "./islands/GenderPredictor.tsx": $GenderPredictor,
    "./islands/Header.tsx": $Header,
    "./islands/ModelInfo.tsx": $ModelInfo,
    "./islands/TabNavigation.tsx": $TabNavigation,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
